---
default_language_version:
     python: python3.13
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.29.1
    hooks:
    - id: django-upgrade
      args: [--target-version, "5.2"]

  - repo: https://github.com/ambv/black
    rev: 25.12.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-check

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py313-plus
