---
default_language_version:
     python: python3.13
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.29.1
    hooks:
    - id: django-upgrade
      args: [--target-version, "6.0"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
