# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectversion',
            options={'ordering': ('-sortable_version_number',)},
        ),
        migrations.AddField(
            model_name='projectversion',
            name='sortable_version_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
