# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbv", "0002_auto_20161106_0952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="function",
            name="module",
        ),
        migrations.DeleteModel(
            name="Function",
        ),
    ]
