# Generated by Django 2.0 on 2018-03-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0003_remove_function_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klassattribute',
            name='value',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='moduleattribute',
            name='value',
            field=models.CharField(max_length=511),
        ),
    ]
