# Generated by Django 3.1.13 on 2021-12-02 00:12
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cbv", "0004_larger_attribute_values"),
    ]
    operations = [
        migrations.DeleteModel(name="ModuleAttribute"),
    ]
