# Generated by Django 3.1.14 on 2022-12-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbv", "0005_delete_moduleattribute"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectversion",
            unique_together={("version_number",)},
        ),
    ]
