# Generated by Django 3.1.14 on 2022-12-29 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cbv", "0006_simplify_unique_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectversion",
            name="project",
        ),
    ]
