# Generated by Django 3.1.14 on 2022-12-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbv", "0008_delete_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectversion",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="projectversion",
            constraint=models.UniqueConstraint(
                fields=("version_number",), name="unique_number_per_version"
            ),
        ),
    ]
