name: Python tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86  # v5.4.2

      - name: Run pre-commit
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run Python tests
        run: |
          make test

      - name: Check mypy ratchet for changes
        run: |
          make mypy
