name: Python tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.*.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.prod.txt -r requirements.dev.txt

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run Python tests
        run: |
          make test

      - name: Check mypy ratchet for changes
        run: |
          make mypy
